"""invoices

Immutable per-recharge invoice, generated by services/invoicing.py the
moment a Razorpay payment.captured webhook credits a wallet — see
.claude/specs/21-invoicing.md. invoice_number_seq backs invoice_number
generation (app code calls nextval(), never a column default) so numbering
stays gap-free and safe under concurrent recharges without locking the
invoices table itself.

Revision ID: 0022
Revises: 0021
Create Date: 2026-07-19

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0022"
down_revision = "0021"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE invoice_number_seq")
    op.create_table(
        "invoices",
        sa.Column(
            "invoice_id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("wallet_transaction_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("invoice_number", sa.String(), nullable=False),
        sa.Column("sac_code", sa.String(), server_default="9983", nullable=False),
        sa.Column("taxable_value_inr", sa.Numeric(), nullable=False),
        sa.Column("cgst_rate_percent", sa.Numeric(), server_default="9.00", nullable=False),
        sa.Column("sgst_rate_percent", sa.Numeric(), server_default="9.00", nullable=False),
        sa.Column("cgst_amount_inr", sa.Numeric(), nullable=False),
        sa.Column("sgst_amount_inr", sa.Numeric(), nullable=False),
        sa.Column("total_inr", sa.Numeric(), nullable=False),
        sa.Column("currency", sa.String(), server_default="INR", nullable=False),
        sa.Column(
            "service_description",
            sa.String(),
            server_default="Cardex Recharge - For Visiting Card Parsing,Enrichment and Scoring",
            nullable=False,
        ),
        sa.Column("bill_to_name", sa.String(), nullable=False),
        sa.Column("bill_to_gst_no", sa.String(), nullable=True),
        sa.Column("bill_to_billing_address", sa.String(), nullable=True),
        sa.Column("issuer_name", sa.String(), nullable=False),
        sa.Column("issuer_gst_no", sa.String(), nullable=False),
        sa.Column("issuer_address", sa.String(), nullable=False),
        sa.Column("terms_and_conditions", sa.Text(), nullable=False),
        sa.Column("pdf_storage_key", sa.String(), nullable=False),
        sa.Column(
            "issued_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("invoice_id", name="pk_invoices"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"],
            name="fk_invoices_user_id_users",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.org_id"],
            name="fk_invoices_org_id_organizations", ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["wallet_transaction_id"], ["wallet_transactions.wallet_transaction_id"],
            name="fk_invoices_wallet_transaction_id_wallet_transactions",
        ),
        sa.UniqueConstraint("wallet_transaction_id", name="uq_invoices_wallet_transaction_id"),
        sa.UniqueConstraint("invoice_number", name="uq_invoices_invoice_number"),
    )
    op.create_index("ix_invoices_user_id_issued_at", "invoices", ["user_id", "issued_at"])
    op.create_index("ix_invoices_org_id_issued_at", "invoices", ["org_id", "issued_at"])


def downgrade() -> None:
    op.drop_index("ix_invoices_org_id_issued_at", table_name="invoices")
    op.drop_index("ix_invoices_user_id_issued_at", table_name="invoices")
    op.drop_table("invoices")
    op.execute("DROP SEQUENCE invoice_number_seq")
